name: go-test
on:
  push:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu:jammy-20220531
    steps:
      - name: Setup container
        run: |
          apt-get update
          apt-get install -y --no-recommends \
            apt-transport-https \
            ca-certificates \
            curl \
            gcc \
            git \
            golang \
            make \
            sudo

      - name: Check out code
        uses: actions/checkout@v1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v16

      # TODO: Fix docker caching
      - name: Pull docker images
        run: docker-compose -f test/docker/docker-compose.yml pull

      - name: Check need rebuild Docker images
        run: |
          echo "need_rebuild=true" >> $GITHUB_ENV

      - name: Create cache directory
        run: mkdir -p /home/runner/.cache/go-build

      - name: Pull build docker images
        if: env.need_rebuild
        run: |
          docker pull ubuntu:jammy-20220531

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Build docker images
        if: env.need_rebuild
        run: |
          make docker_compose_build
          docker image rm ubuntu:jammy-20220531
          docker image prune -f

      - name: Run tests
        run: echo $PATH $GOPATH && go version && find / -name protoc-gen-openapi && make docker_test_no_build || ( docker-compose -f test/docker/docker-compose.yml logs && false )
        shell: bash
        env:
          TEST_PARAM: "-coverprofile=coverage.out -covermode=atomic"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
